apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deployment
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/app-of-apps/deployment
    repoURL: https://github.com/cjfaraon-okta/test
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: job
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
#    argocd.argoproj.io/hook: PreSync
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-cd/app-of-apps/job
    repoURL: https://github.com/cjfaraon-okta/test
    targetRevision: HEAD