apiVersion: batch/v1
kind: Job
metadata:
  name: before-1
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["sleep", "10"]
#          command: [ "false" ]
      restartPolicy: Never
  backoffLimit: 0